defmodule Verb do
  defstruct infinitive: nil,
            aspect: nil,
            present_first_singular: nil,
            present_second_singular: nil,
            present_third_singular: nil,
            present_first_plural: nil,
            present_second_plural: nil,
            present_third_plural: nil,
            future_first_singular: nil,
            future_second_singular: nil,
            future_third_singular: nil,
            future_second_plural: nil,
            future_first_plural: nil,
            future_third_plural: nil,
            past_singular_masculine: nil,
            past_singular_feminine: nil,
            past_singular_neuter: nil,
            past_plural: nil,
            imperative_second_singular: nil,
            imperative_second_plural: nil,
            present_active_participle: nil,
            past_active_participle: nil,
            present_passive_participle: nil,
            past_passive_participle: nil,
            present_adverbial_participle: nil,
            past_adverbial_participle: nil
end
